# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_operacoes.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Op(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        MainWindow.setToolTip("<html><head/><body><p align=\"center\"><img src=\":/newPrefix2/deposito.png\"/></p></body></html>")
        MainWindow.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 0, 171, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/operacao.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 110, 111, 31))
        self.pushButton.setStyleSheet("image: url(:/newPrefix2/deposito.png);\n"
"background-color: rgb(38, 54, 200);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 110, 91, 31))
        self.pushButton_2.setAcceptDrops(True)
        self.pushButton_2.setStyleSheet("image: url(:/newPrefix/saque.png);\n"
"background-color: rgb(38, 54, 200);\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 180, 111, 31))
        self.pushButton_3.setStyleSheet("image: url(:/newPrefix/transferencia.png);\n"
"background-color: rgb(38, 54, 200);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 180, 91, 31))
        self.pushButton_4.setStyleSheet("image: url(:/newPrefix/extrato.png);\n"
"background-color: rgb(38, 54, 200);")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 250, 111, 31))
        self.pushButton_5.setStyleSheet("image: url(:/newPrefix/historico.png);\n"
"background-color: rgb(38, 54, 200);")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(300, 250, 91, 31))
        self.pushButton_6.setStyleSheet("image: url(:/newPrefix/sair.png);\n"
"background-color: rgb(170, 0, 0);")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
from telas.rcs import dep_rc
from telas.rcs import op_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Op()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
